# License: LGPL-3.0-or-later
name: NOTICE-js update
env:
  node: 14.6.0
  os: ubuntu-20.04
on: 
  workflow_run:
    workflows: ["NOTICE-js verification"]
    types:
      - completed
jobs:
  notice_js:
    runs-on: ubuntu-20.04
    steps:
      - name: download branch
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: notice_js.yml
          branch: ${{ github.head_branch }}
          name: branch_to_update
          workflow_conclusion: 'failure'
      - name: Read branch.txt
        id: branch
        uses: juliangruber/read-file-action@v1
        with:
          path: ./branch.txt
      - name: checkout code
        uses: actions/checkout@v2
        with: 
          ref: ${{ steps.branch.outputs.content }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}
          cache: 'npm'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}
          cache: 'npm'

      - name: Update NOTICE-js on Dependabot
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: |
          npm run notice:js:update
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add NOTICE-js
          git commit -m "Update NOTICE-js"
          git push
      
